{
 "title": "Weather Stations",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "MQTT Uptime",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mqtt-logging\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"log\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"broker_uptime\")"
    }
   ]
  },
  {
   "title": "Rain",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"flwsb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather_station\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rain\")\r\n  "
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "description": "0-100%",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"flwsb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather_station\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")"
    }
   ]
  },
  {
   "title": "Weather Station 1",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"flwsb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather_station\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"weather-station-1\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"flwsb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather_station\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temp\")"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"flwsb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather_station\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"wind_speed\")"
    }
   ]
  },
  {
   "title": "Weather Station 2",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"flwsb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather_station\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"weather-station-2\")"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"flwsb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather_station\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"wind_direction\")"
    }
   ]
  },
  {
   "title": "Wind Gust",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"flwsb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather_station\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"wind_gust\")"
    }
   ]
  }
 ]
}